[package]
name = "blindfold-chess"
version = "0.1.0"
authors = ["Lucas Radaelli <lucasradaelli@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgn-reader = "0.15.0"
pleco = "0.5.0"